#!/bin/bash

echo "===== Wardy App Supabase Setup Helper ====="
echo ""
echo "This script will guide you through setting up your Supabase project for the Wardy app."
echo ""
echo "IMPORTANT: You need to have already created a Supabase project at https://app.supabase.com"
echo ""

echo "Step 1: Execute the SQL script (CRITICAL)"
echo "----------------------------------------"
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to the 'SQL Editor' section"
echo "3. Create a new query"
echo "4. Copy and paste the ENTIRE SQL script from supabase_setup.sql"
echo "5. Click 'Run' to execute the script"
echo ""
echo "IMPORTANT: If you've already created the table with incorrect column names,"
echo "you should drop it first with: DROP TABLE IF EXISTS clothing_items CASCADE;"
echo ""
echo "The SQL script will create the clothing_items table with the correct column names:"
echo "- id (UUID)"
echo "- name (TEXT)"
echo "- category (TEXT)"
echo "- imagepath (TEXT) - note the lowercase 'p'"
echo "- dateadded (TIMESTAMP) - note the lowercase 'd'"
echo "- metadata (JSONB)"
echo ""
echo "PostgreSQL is case-sensitive, so these column names MUST match exactly!"
echo ""

echo "Step 2: Create the Storage Bucket"
echo "--------------------------------"
echo "1. In your Supabase project dashboard, go to the 'Storage' section"
echo "2. Click 'Create a new bucket'"
echo "3. Name the bucket 'clothing_images' (exactly as written, case-sensitive)"
echo "4. Set the privacy setting to 'Public' to allow public access to the images"
echo "5. Click 'Create bucket'"
echo ""

echo "Step 3: Configure Storage Bucket Policies"
echo "----------------------------------------"
echo "After creating the bucket, you need to set up access policies:"
echo ""
echo "1. In the Storage section, select the 'clothing_images' bucket"
echo "2. Go to the 'Policies' tab"
echo "3. Add the following policies:"
echo ""
echo "For reading files:"
echo "- Click 'Add Policy'"
echo "- Select 'For SELECT operations (read)' from the dropdown"
echo "- Policy name: 'Allow public read access'"
echo "- Policy definition: Select 'Custom policy' and enter 'true'"
echo "- Click 'Save Policy'"
echo ""
echo "For inserting files:"
echo "- Click 'Add Policy'"
echo "- Select 'For INSERT operations (create)' from the dropdown"
echo "- Policy name: 'Allow anonymous uploads'"
echo "- Policy definition: Select 'Custom policy' and enter 'true'"
echo "- Click 'Save Policy'"
echo ""
echo "For updating files:"
echo "- Click 'Add Policy'"
echo "- Select 'For UPDATE operations (update)' from the dropdown"
echo "- Policy name: 'Allow anonymous updates'"
echo "- Policy definition: Select 'Custom policy' and enter 'true'"
echo "- Click 'Save Policy'"
echo ""
echo "For deleting files:"
echo "- Click 'Add Policy'"
echo "- Select 'For DELETE operations (delete)' from the dropdown"
echo "- Policy name: 'Allow anonymous deletes'"
echo "- Policy definition: Select 'Custom policy' and enter 'true'"
echo "- Click 'Save Policy'"
echo ""

echo "Step 4: Restart Your App"
echo "----------------------"
echo "After completing these steps, restart your Flutter app."
echo "The errors should be resolved, and your app should be able to connect to Supabase,"
echo "store data in the database, and upload/retrieve images from the storage bucket."
echo ""

echo "===== Setup Guide Complete ====="
echo "Follow these steps carefully to ensure your app works correctly with Supabase."
echo "" 